controllers/MessageController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\controllers\BaseController;
use yii\filters\VerbFilter;
use app\models\UploadForm;
use yii\web\BadRequestHttpException;

class MessageController extends BaseController
{
	
	public $numberOfMessagesOnPage;
		
    public function init()
    {
        parent::init();
        $this->numberOfMessagesOnPage = Yii::$app->params['numberOfMessagesOnPage'];
		$footer_data = json_decode(self::sendCurl('', [], "/site/get-footer-data"));
		$this->view->params['footer_post'] = $footer_data->posts;
		$this->view->params['footer_history'] = $footer_data->history_page;
        $this->view->registerJsFile('/js/bootstrap-datepicker.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->view->registerCssFile('/css/datepicker.css');
        $this->view->registerCssFile('/css/jquery-ui.min.css');
        $this->view->registerJsFile('/js/common.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->view->registerJsFile('/js/account.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->view->registerJsFile('/js/message.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->view->registerJsFile('/js/jquery-ui.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
    }
    
    public function beforeAction($action)
	{            
		$this->enableCsrfValidation = false;
	    return parent::beforeAction($action);
	}
    
    public function actionIndex()
    {
    	$session = Yii::$app->session;
		$ajax = Yii::$app->request->getIsAjax();
		
    	if (!$this->checkIfUserLoggedIn()) {            
            $this->redirect('/', 301);
        } 
		
		$offset = 0;
		$page = 1;		
		$searchParams = null;
		
		if (isset($session['letters_search_params'])) {
			unset($session['letters_search_params']);
		};
		
		if ($ajax) {
			$page = Yii::$app->request->post('page');			
			$searchParams = Yii::$app->request->post('searchParams');
			$session->set('letters_search_params', $searchParams);
		}
		
		if (empty($page) || $page < 0) {
			$page = 1;
		}
		$offset = ($page - 1) * $this->numberOfMessagesOnPage;
		$params = [
	        'skinID' => 1,	       
	        'limit' => $this->numberOfMessagesOnPage,
	        'offset' => $offset,
	        'type' => 'inbox',	        
	        'searchParams' => $searchParams,
        ];
		
		$result = json_decode(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); 
		//var_dump(self::sendCurl($session['user_token'], $params, "/v1/letter/get-letters")); die;
		if (!self::checkCurlResponse($result)) {
			return $this->redirect('/', 301);
        }

		$params = [
	        'skinID' => 1,	        
	        'limit' => $this->numberOfMessagesOnPage,
	        'offset' => $offset,
	        'type' => 'outbox',	        
	        'searchParams' => $searchParams,
        ];

        $result2 = json_decode(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters"));
		//var_dump(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); die;
		
		if (!self::checkCurlResponse($result2)) {
			return $this->redirect('/', 301);
        }

        $params = [
	        'limit' => $this->numberOfMessagesOnPage,
	        'offset' => $offset,
	        'type' => 'system'
        ];
		
		$result3 = json_decode(self::sendCurl($session['user_token'], $params, "/v1/message/get-messages")); 
		//var_dump(self::sendCurl($session['user_token'], $params, "/v1/message/get-messages")); die;	
		if (!self::checkCurlResponse($result3)) {
			return $this->redirect('/', 301);
        }
				
		$params = [
	        'skinID' => 1,	        
	        'limit' => $this->numberOfMessagesOnPage,
	        'offset' => $offset,
	        'type' => 'deleted',
	        'searchParams' => $searchParams,
        ];
		
		$result4 = json_decode(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); 
		//var_dump(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); die;
		if (!self::checkCurlResponse($result4)) {
			return $this->redirect('/', 301);
        }
		$this->view->registerJs(self::JS_GET_MESSAGE_COUNT, yii\web\View::POS_READY);
		$this->verticalMenuName = "inbox";
		$this->horizontalMenuName = "message";
		
		if ($ajax) {
			$messages = Yii::$app->controller->renderPartial('//message/inbox.php', [
				'inboxLettersArray' => $result->lettersArray, 
				'inboxLettersCount' => $result->countLetters,
				'outboxLettersArray'  => $result2->lettersArray, 
				'outboxLettersCount' => $result2->countLetters,
				'deletedLettersArray' => $result4->lettersArray,
				'deletedLettersCount' => $result4->countLetters, 
				'systemLettersArray' => $result3->messageArray,
				'systemLettersCount' => $result3->count,
				'featuredIDs' => $result->featuredIDs, 
				'blackListIDs' => $result->blackListIDs,
				'page' => $page
			]);
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        	return $messages;
		}
        
		return $this->render('inbox', [
			'inboxLettersArray' => $result->lettersArray, 
			'inboxLettersCount' => $result->countLetters,
			'outboxLettersArray'  => $result2->lettersArray, 
			'outboxLettersCount' => $result2->countLetters,
			'deletedLettersArray' => $result4->lettersArray,
			'deletedLettersCount' => $result4->countLetters,			
			'systemLettersArray' => $result3->messageArray,
			'systemLettersCount' => $result3->count,
			'featuredIDs' => $result->featuredIDs, 
			'blackListIDs' => $result->blackListIDs, 
			'page' => $page,
			'limit' => $this->numberOfMessagesOnPage
		]);
    }
    
    public function actionNew()
    {
    	return $this->redirect('/messages');
    	$session = Yii::$app->session;
		$ajax = Yii::$app->request->getIsAjax();
				
    	if (!$this->checkIfUserLoggedIn()) {            
            $this->redirect('/', 301);
        }
		
		$offset = 0;
		$page = 1;		
		$searchParams = null;
		
		if (isset($session['letters_search_params'])) {
			unset($session['letters_search_params']);
		};
		
		if ($ajax) {
			$page = Yii::$app->request->post('page');
			$searchParams = Yii::$app->request->post('search_params');
			$session->set('letters_search_params', $searchParams);
		}
		
		if (empty($page) || $page < 0) {
			$page = 1;
		}
		$offset = ($page - 1) * $this->numberOfMessagesOnPage;
		$params = [
	        'skinID' => 1,	        	        
	        'limit' => $this->numberOfMessagesOnPage,
	        'offset' => $offset,
	        'type' => 'new',	        
	        'searchParams' => $searchParams,
        ];
		
		$result = json_decode(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); 
		//var_dump(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); die;
		if (!self::checkCurlResponse($result)) {
			return $this->redirect('/', 301);
        }
        
        $this->verticalMenuName = "new";
		$this->horizontalMenuName = "message";
        
        if ($ajax) {        	
			$messages = Yii::$app->controller->renderPartial('//message/new.php', [
				'lettersArray' => $result->lettersArray, 
				'lettersCount' => $result->countLetters, 
				'featuredIDs' => $result->featuredIDs, 
				'blackListIDs' => $result->blackListIDs,
				'page' => $page
			]);
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        	return $messages;
		}
		
		$this->view->registerJs(self::JS_GET_MESSAGE_COUNT, Yii\web\View::POS_READY);
                
        return $this->render('new', [
			'lettersArray' => $result->lettersArray, 
			'lettersCount' => $result->countLetters, 
			'featuredIDs' => $result->featuredIDs, 
			'blackListIDs' => $result->blackListIDs,
        	'page' => $page,
        	'limit' => $this->numberOfMessagesOnPage
        ]);
		
    }
    
    public function actionSingle($messageID)
    {
		$session = Yii::$app->session;
		$ajax = Yii::$app->request->getIsAjax();				
		
		$params = [
	        'type' => 'single',
	        'letterID' => $messageID,
        ];
		
		$result = $this->getResponseFromAPI($params, "/v1/letter/get-letters");
		//var_dump(self::sendCurl($session['user_token'], $params,"/v1/letter/get-letters")); die; 
			
		if (!isset($result->lettersArray[0]) || empty($result->lettersArray[0])) {			
			$session->set('message', 'Letter not exists or was deleted');
			return $this->redirect('/', 301);
		}
		
		if ($result->lettersArray[0]->another_user_avatar != null) {
			$result->lettersArray[0]->another_user_avatar = $this->serverUrl . "/" . $result->lettersArray[0]->another_user_avatar;
	    } else {
			$result->lettersArray[0]->another_user_avatar = "/img/no_avatar_normal.jpg";
	    }
		
		$anotherUserID = $result->lettersArray[0]->another_user_id;
		
		$lettersType = isset($result->letterType->type) ? $result->letterType->type : null;
		
		$readMessageScript = "window['messageLibrary']['getLettersAlbum'](); " . self::JS_GET_MESSAGE_COUNT;
		
		if ($lettersType != 'outbox') {
			$readMessageScript .= "window['messageLibrary']['readMessage']($messageID);";
		}
		
		$this->view->registerJsFile('/js/tinymce/tinymce.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
		$this->view->registerJsFile('/js/upload_img.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
		$this->view->registerJsFile('/js/jquery.form.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
		$this->view->registerJs($readMessageScript, yii\web\View::POS_READY);
						
		if ($ajax) {
			$messages = Yii::$app->controller->renderPartial('//message/message-template.php', [
				'lettersData'=>$result->lettersArray[0],
				'next_prev'=>$result->next_prev_letters_ids
			]);
        	
        	$from = Yii::$app->params['adminEmail']; 
        	if (YII_DEBUG) {
        		$to = 'darkstill@ukr.net';
        	} else {
        		$to = $session['user_data']['email'];
        	}
        	
        	if ($session['user_data']['email'] == "") {
        		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

views/layouts/parts/-shop-filter-block2.php
<span data-value="all" class="fl-l custom-border main-col-text <?=(empty($giftsCategories)) ? 'active':'';?>">all gifts</span>
<?php foreach ($allGiftsCategories as $category) { ?>
	<span data-value="<?= $category['id'] ?>" class="fl-l custom-border main-col-text <?=(in_array($category['id'], $giftsCategories)) ? 'active':'';?>"><?= $category['title'] ?></span>
<?php } ?>

views/layouts/parts/-shop-sort-block2.php
<div class="sort_by fl-l">
    <span>Sort by price:</span>
    <a href="javascript:void(0);" <?=isset($sort) && $sort == 'asc' ? 'class="active"':'';?> data-value="asc" title="Asc">
        <span class="to_up_price custom-border"> <i class="fa fa-long-arrow-up" aria-hidden="true"></i>
        </span>
    </a>
    <a href="javascript:void(0);" <?=isset($sort) && $sort == 'desc' ? 'class="active"':'';?> data-value="desc" title="Desc">
        <span class="to_up_price custom-border"> <i class="fa fa-long-arrow-down" aria-hidden="true"></i>
        </span>
    </a>
</div>

views/layouts/parts/footer.php
<?php
    use app\controllers\BaseController;
    use yii\helpers\Html;
    $session = Yii::$app->session;
    $userType = (isset($session['user_data']['userType']) &&  $session['user_data']['userType'] == BaseController::USER_FEMALE) ? BaseController::USER_FEMALE : BaseController::USER_MALE;
    $suffix = ($userType == BaseController::USER_MALE) ? 'girls' : 'men';
?>
<footer class="main-footer">
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4 footer-column footer-column-1">
                    <div class="footer-content-item">
                        <h5 class="footer-content-item-title">Company history</h5>
                        <p class="history-text"><?=Html::decode($footer_history) ?></p>
                    </div>
                    <div class="footer-content-item">
                        <h5 class="footer-content-item-title">Sign up for our newsletter</h5>
                        <form action="/subscribe" class="news-form" method="post">
                            <input type="email" name="email" placeholder="Never miss a deal again" required>
                            <button type="submit">
                                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 footer-column footer-column-2">
                    <div class="footer-content-item footer-socials-wrapper">
                        <h5 class="footer-content-item-title">Social media:</h5>
                        <ul class="socials list-inline">
                            <li><a href="javascript:void(0);"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                            <li><a href="javascript:void(0);"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="javascript:void(0);"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                            <li><a href="javascript:void(0);"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        </ul>
                        <a href="/search" class="btn">Find Single <?= $suffix ?></a>
                        <div class="card-block">
	                        <h5 class="footer-content-item-title">We accept:</h5> 
	                        <ul class="socials list-inline">
	                        	<li class="credit-card"><i class="fa fa-cc-visa" aria-hidden="true"></i> </li>
	                        	<li class="credit-card"><i class="fa fa-cc-mastercard" aria-hidden="true"></i></li>
	                    	</ul>
                        </div>                        
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 footer-column footer-column-3">
                    <div class="footer-content-item">
                        <h5 class="footer-content-item-title">Recents posts:</h5>
                        <?php if(!empty($footer_posts)) {
                            foreach ($footer_posts as $one) {?>
                                <div class="footer-post">
                                    <h6 class="footer-post-date"><span class="date"><?=date("M d Y",strtotime($one->created_at))?></span> | <span class="post-autor">By Admin</span></h6>
                                    <a href="/blog/<?=$one->id?>" class="footer-post-title"><?=$one->title?></a>
                                    <p class="footer-post-description"><?=mb_substr($one->description,0,100,'utf8')?>...</p>
                                </div>
                            <?php }
                        } ?>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-2 footer-column footer-column-4">
                    <div class="footer-content-item">
                        <h5 class="footer-content-item-title">Navigation</h5>
                        <ul class="footer-menu arrows-list">
                            <?php if ($userType == BaseController::USER_MALE) {?>
                            <li class="with-online"><a href="/girls/online">Girls Online<span class="online">0</span></a></li>
                            <li><a href="/girls">All Girls</a></li>
                            <li><a href="/girls/new">New Girls</a></li>
                            <?php } else {?>
                            <li class="with-online"><a href="/men/online">Men Online<span class="online">0</span></a></li>
                            <li><a href="/men">All Men</a></li>
                            <li><a href="/men/new">New Men</a></li>            
                            <?php } ?>
                            <li><a href="/about">About us</a></li>
                            <li><a href="#" data-toggle="modal" data-target="#modalContact">Contact</a></li>                            
                        </ul>
                        <p>Customer Support: <a href="mailto:support@test.com">support@test.com</a></p>
                    </div>
                </div>
        </div>
    </div>
</div>
    <div class="footer-bottom-line">
        <p class="copy">Copyright &copy; LIFETIME.DATING <?= date('Y'); ?>. All rights reserved.</p>
        <p class="copy"><a href="/privacy-policy">Privacy policy</a></p>
    </div>
    <?= \bizley\cookiemonster\CookieMonster::widget([
            'box' => [
                'view' => '@app/views/layouts/cookie',
                'classButton' => 'cookie-button',
                'classInner' => 'cookie-inner',
                'classOuter' => 'cookie-block',
                'addOuterStyle' => [
                    'display' => 'none'
                ]
            ],
            'content' => [
                //'buttonMessage' => 'OK', // instead of default 'I understand'
            ],
            'mode' => 'custom'
        ]);
    ?>
</footer>

views/layouts/parts/girl-tile-black-list.php
<?php 
$server_url = $this->context->server_url;
$date_create = strtotime($womans->date_create);
//если пользоватлеь добавлен мение месяца назад, то ему добавляется значек NEW
$new_label = ((time() - $date_create) <= 60*60*24*30) ? '<li class="is-new fl-r rounded-block">NEW</li>': "";
$avater = !empty($womans->thumb_normal) ? $server_url.'/'.$womans->thumb_normal : '/img/no_avatar_normal.jpg';

if(isset($womans->in_favorite) && $womans->in_favorite == 1){
	$show_status = 'hidden';
	$show_status2 = '';
}else{
	$show_status = '';
	$show_status2 = 'hidden';
}
$prefix = (isset($user_type) && $user_type == 2) ? 'men' : 'girls';
?>
<div class="girl-tile pos-rel" data-user-id="<?=$womans->user_id;?>">
    <div class="girl-photo pos-rel" style="background-image:url(<?=$avater;?>);">
        <ul class="status text-white pos-abs">
            <!--<li class="is-webcam">live<br/>Cam</li>-->
            <?=$new_label;?>
            <!--<li class="is-new">NEW</li>-->
            <!--<li class="is-online">online</li>-->

        </ul>
    </div>
    <div class="girl-meta">
        <div class="meta-left fl-l">
            <div class="girl-name"><?=$womans->first_name;?></div>
            <div class="girl-id"><?=$womans->user_id;?></div>  
        </div>
        <div class="meta-right fl-l black-list-control">
			<a class="link_blacklist fl-r pos-abs" href="/account/delete-form-blacklist/<?=$womans->user_id;?>">
				<i class="fa fa-times text-black" aria-hidden="true"></i>
				<span data-atr="dell">Delete from blacklist</span>
			</a>
        </div>
    </div>
    <a href="<?="/".$prefix."/".$womans->user_id;?>" class="girl-link pos-abs"></a>
</div>

views/layouts/parts/message_selector.php
<?php 
    $session = Yii::$app->session;
    $page_name = (!empty($pageName)) ? $pageName : $this->context->verticalMenuName;

    if ($page_name == 'deleted') {
    	$linkName = 'Restore';
    	$class = 'undo';
    	$aLink = 'restore_link';
    } else {
    	$linkName = 'Delete';
    	$class = 'trash-o';
    	$aLink = 'delete_link';
    }
?>
<ul class="control-list list-inline">
	<li>
		<div class="type-list-box">
			<span class="select-tap select-all"></span>
			<span class="select-type"><i class="fa fa-angle-down" aria-hidden="true"></i></span>
			<ul class="message-option-list type-list">
				<li class="check-all"><a href="javascript:void(0);">Check All</a></li>
				<li class="uncheck-all"><a href="javascript:void(0);">Uncheck All</a></li>
				<li class="check-new"><a href="javascript:void(0);">New messages</a></li>
				<li class="check-answered"><a href="javascript:void(0);">Answered messages</a></li>
			</ul>
		</div>
	</li>
	<li>
		<a href="javascript:void(0);" class="delete-message <?= $aLink; ?> <?= $page_name ?>"><i class="fa fa-<?=$class?>" aria-hidden="true"></i><?= $linkName ?></a>
	</li>
	<?php if( $page_name != 'system' && $page_name != 'deleted'){?>
	<li>
		<?php if ($page_name != 'featured') { ?>
		<a href="javascript:void(0);" class="add-featured"><i class="fa fa-bookmark-o" aria-hidden="true"></i>Add to favourite</a>
		<?php } else { ?>
		<a href="javascript:void(0);" class="add-featured"><i class="fa fa-bookmark-o" aria-hidden="true"></i>Delete from favourite</a>
		<?php } ?>
	</li>
	<?php if (false) {?>
	<li>
		<a href="javascript:void(0);" class="blacklist"><i class="fa fa-times" aria-hidden="true"></i>Add to blacklist</a>
	</li>
	<?php } ?>
	<?php } ?>
</ul>

views/layouts/parts/profile-vertical-menu-man.php
<?php
    use app\controllers\BaseController;
    use yii\helpers\Url;
    $pageName = $this->context->verticalMenuName;
    $session = Yii::$app->session;    
    $userType = (isset($session['user_data']['userType']) &&  $session['user_data']['userType'] == BaseController::USER_FEMALE) ? BaseController::USER_FEMALE : BaseController::USER_MALE;
    if ($userType == BaseController::USER_FEMALE) {
        $baseUrl = 'men';
        $text = 'Men';
        $baseUrl2 = 'girls';
        $text2 = 'Ladies';
    } else {
        $baseUrl = 'girls';
        $text = 'Ladies';
        $baseUrl2 = 'men';
        $text2 = 'Men';
    }   
?>

<div class="side-menu-block members-area">
    <a href="javascript:void(0);" class="side-menu-button">Members Area</a>
    <ul class="side-menu">
        <li class="messages-link"><a href="<?= Url::toRoute('message/index'); ?>">My Messages</a></li>
        <li><a href="/account/edit/<?= $session['user_data']['userID'] ?>">My Account Options</a></li>
        <li><a href="/account/favorite">My Favorites</a></li>
        <li><a href="/account/gallery">My Gallery</a></li>
        <li><a href="/account/video">My Video Gallery</a></li>
        <li><a href="/account/my-gifts">My Gifts</a></li>
        <li><a id="logout_btn" href="javascript:void(0);" onclick="window['commonLibrary']['logout']()">Logout</a></li>
    </ul>
</div>

<div class="side-menu-block profiles">
    <a href="javascript:void(0);" class="side-menu-button">Profiles</a>
    <ul class="side-menu">
        <li><a href="/search">Search</a></li>
        <li><a href="/<?= $baseUrl ?>/online">Online Now <span class="online"></span></a></li>
        <li><a href="/<?= $baseUrl ?>/new">New Profiles</a></li>
        <li><a href="/account/chat">Video Chat</a></li>
        <li class="chat-link"><a href="/account/chat">Text Chat</a></li>
        <!-- <li><a href="javascript:void(0);">Intro Videos</a></li> -->
    </ul>
</div>

<!-- <div class="side-menu-block services">
    <a href="javascript:void(0);" class="side-menu-button">Services</a>
    <ul class="side-menu">
        <li><a href="javascript:void(0);">Live Video Chat</a></li>
        <li><a href="javascript:void(0);">Serious Dater Program</a></li>
        <li><a href="javascript:void(0);">Member Rewards</a></li>
        <li><a href="javascript:void(0);">Apartment Rental</a></li>
        <li><a href="javascript:void(0);">Singles Tours</a></li>
    </ul>
</div> -->

<div class="side-menu-block info">
    <a href="javascript:void(0);" class="side-menu-button">Information</a>
    <ul class="side-menu">
        <li><a href="/blog">Love Stories</a></li>
        <li><a href="/contact">Contact Us</a></li>
        <li><a href="/about">About Us</a></li>
    </ul>
</div>

views/layouts/parts/profile-vertical-menu.php
<?php
    use app\controllers\BaseController;
    use yii\helpers\Url;
    $pageName = $this->context->verticalMenuName;
    $session = Yii::$app->session;    
?>
<div class="sidebar-block profile-main-action-block">
    <ul class="profile-menu-list main-action-menu">
        <li><a href="/account/chat" class="live-chat-link"><span>Live Chat</span> </a></li>
        <li class="has-action-submenu">
            <a href="javascript:void(0);" class="messages-link"><span>Messages</span> </a>
            <ul class="main-action-submenu">
                <li <?php if (Yii::$app->controller->action->id == 'inbox') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/inbox'); ?>"><span class="inbox">Inbox message</span></a></li>
                <li <?php if (Yii::$app->controller->action->id == 'outbox') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/outbox'); ?>">Outbox message</a></li>
                <li <?php if (Yii::$app->controller->action->id == 'new') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/new'); ?>">New message</a></li>
                <li <?php if (Yii::$app->controller->action->id == 'featured') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/featured'); ?>">Favorite message</a></li>
                <li <?php if (Yii::$app->controller->action->id == 'deleted') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/deleted'); ?>">Deleted message</a></li>                
                <li <?php if (Yii::$app->controller->action->id == 'system') {echo 'class="active"';} ?>><a href="<?= Url::toRoute('message/system'); ?>"><span class="system">System message</span></a></li>
            </ul>
        </li>
        <li><a href="/account/my-gifts" class="gifts-link">Gifts</a></li>
    </ul>
</div>

<div class="sidebar-block profile-categories-block">
    <ul class="profile-menu-list profile-categories-list">
        <li <?php if($pageName == "favorite"){echo 'class="active"';}?>><a href="/account/favorite">My favorites</a></li>
        <li <?php if($pageName == "guests"){echo 'class="active"';}?>><a href="/account/guests">My Guests</a></li>
        <li <?php if($pageName == "gallery"){echo 'class="active"';}?>><a href="/account/gallery">My gallery</a></li>
        <li <?php if($pageName == "video"){echo 'class="active"';}?>><a href="/account/video">My video</a></li>
        <li <?php if($pageName == "winks"){echo 'class="active"';}?>><a href="/account/winks">Winks</a></li>
        <li <?php if($pageName == "blacklist"){echo 'class="active"';}?>><a href="/account/blacklist">Blacklist</a></li>
    </ul>
</div>

views/layouts/parts/shop-filter-block.php
<span data-value="all" class="fl-l custom-border main-col-text <?=(empty($giftsCategories)) ? 'active':'';?>">all gifts</span>
<?php foreach ($allGiftsCategories as $category) { ?>
	<span data-value="<?= $category['id'] ?>" class="fl-l custom-border main-col-text <?=(in_array($category['id'], $giftsCategories)) ? 'active':'';?>"><?= $category['title'] ?></span>
<?php } ?>